[package]
name = "engine"
version = "0.1.0"
authors = ["benjamin <benji.lef76@gmail.com>"]
edition = "2018"

[dependencies.chess]
path = "../chess"

[dependencies]
actix-web = "3.3.2"
awc = "2.0.3"
futures-util = "0.3.8"