[package]
name = "chess-wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']

[dependencies.chess]
path = "../../../chess"

[dependencies]
js-sys = "*"
wasm-bindgen = "0.2.74"
wee_alloc = "0.4.5"