[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies.chess]
path = "../chess"

[dependencies.engine]
path = "../engine"

[dependencies]
futures = "0.3.15"
tokio = {version = "1.8.1", features = ["macros", "io-util", "rt-multi-thread"]}
tokio-stream = "0.1.7"
warp = "0.3.1"