[package]
name = "server"
version = "0.1.0"
authors = ["benjamin <benji.lef76@gmail.com>"]
edition = "2018"

[dependencies.chess]
path = "../chess"

[dependencies.engine]
path = "../engine"

[dependencies]
actix = "0.10.0"
actix-files = "0.3"
actix-web = "3"
actix-web-actors = "3"
