[package]
name = "server"
version = "0.1.0"
authors = ["benjamin <benji.lef76@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.10.0"
actix-files = "0.5.0"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"
