[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies.chess]
path = "../chess"

[dependencies.engine]
path = "../engine"

[dependencies]
warp = "0.3.1"
tokio = {version = "*", features = ["macros", "io-util", "rt-multi-thread"]}